import { contact } from './contact';

/** Social card generated by scripts/generate-og-image.mjs and committed under public/. */
export const OG_IMAGE = {
  path: '/og-image.jpg',
  width: 1200,
  height: 630,
  alt: 'Logispack Capital Humano: logística, maquila y personal especializado',
} as const;

/** Logo used in structured data; copied verbatim from public/. */
const LOGO_PATH = '/apple-touch-icon.png';

export function absoluteUrl(path: string, site: string | URL): string {
  return new URL(path, site).href;
}

/** LocalBusiness JSON-LD built exclusively from src/lib/contact.ts. */
export function buildOrganizationJsonLd(site: string | URL) {
  return {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: contact.brand,
    url: absoluteUrl('/', site),
    logo: absoluteUrl(LOGO_PATH, site),
    image: absoluteUrl(OG_IMAGE.path, site),
    telephone: contact.phones.map((phone) => phone.href.replace(/^tel:/, '')),
    email: contact.email,
    address: {
      '@type': 'PostalAddress',
      streetAddress: contact.address,
      addressCountry: 'MX',
    },
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
      ],
      opens: '08:00',
      closes: '18:00',
    },
  };
}
